version: '3.3'
services:
  db:
    image: mysql:8.0.30
    restart: always
    container_name: jooq-books-mysql
    environment:
      MYSQL_DATABASE: 'jooq-books'
      MYSQL_USER: 'spring_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: